_find_package(${ARGS})
if(NOT BUILD_SHARED_LIBS AND (NOT CMAKE_SYSTEM_NAME MATCHES "Darwin"))
  if(CMAKE_SYSTEM_NAME MATCHES "Linux")
    list(APPEND clFFT_Extra_Libs m stdc++)
  endif(CMAKE_SYSTEM_NAME MATCHES "Linux")

  if(TARGET clFFT)
      set_property(TARGET clFFT APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${clFFT_Extra_Libs})
  endif()
endif()